### ISSUE TITLE
大家都是只点赞不看的么？有链接失效了

### ISSUE THREAD

**Issue by windard** [xingshaocheng/architect-awesome#126]
大家都是只点赞不看的么？有链接失效了，博客网站打不开了

[《MySQL的InnoDB索引原理详解](http://www.admin10000.com/document/5372.html) 

打不开还好，要是链接变成莫名其妙的网站就尴尬了。😂

**Comment by misland** [comment]
被你发现了，95%应该都是star后就忘了

**Comment by misland** [comment]
> 被你发现了，95%应该都是star后就忘了

也包括我自己

**Comment by 94rain** [comment]
幸运的是这个网页在Wayback Machine有存档：
http://web.archive.org/web/20190430065935/http://www.admin10000.com/document/5372.html
