### ISSUE TITLE
非Java系后端架构师，是不是要学一下Java？

### ISSUE THREAD

**Issue by bgdsh** [xingshaocheng/architect-awesome#55]
Java在后端架构领域发展的已经很好了，对于非Java系后端架构师是否要学一下Java体系的知识，并从中汲取养分？

**Comment by bgdsh** [comment]
#友好地交谈

**Comment by jmcds** [comment]
我就是Java后端研发, 正努力成为架构师, 个人感觉在完成自己工作之余,可以了解下Java 体系, 会有收获.
