### ISSUE TITLE
申请收录 ^_^

### ISSUE THREAD

**Issue by dyc87112** [xingshaocheng/architect-awesome#7]
博客：程序猿DD http://blog.didispace.com
Spring Boot基础教程：http://blog.didispace.com/Spring-Boot%E5%9F%BA%E7%A1%80%E6%95%99%E7%A8%8B/
Spring Cloud基础教程：http://blog.didispace.com/Spring-Cloud%E5%9F%BA%E7%A1%80%E6%95%99%E7%A8%8B/

**Comment by xingshaocheng** [comment]
DONE
