### ISSUE TITLE
建议增加脑图

### ISSUE THREAD

**Issue by yuanmouren1hao** [xingshaocheng/architect-awesome#86]
建议增加脑图

**Comment by weisd** [comment]
建议增加脑图+1

**Comment by dongdong5820** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，邮件我已收到，谢谢您！
            祝您身体健康，天天快快乐乐，生活如如意意！

**Comment by GeniusDSY** [comment]
已经收到你的规划！！！祝你生活愉快！！！学习进步！！！天天开心！！！

**Comment by lumanda** [comment]
已收到。

**Comment by chinyau1** [comment]
您好！
        您的信件已经收到！
                               谢谢！
