### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by ab-chao** [xingshaocheng/architect-awesome#98]
![图片](https://user-images.githubusercontent.com/22811751/58066467-076a8400-7bbc-11e9-8814-9ec58f90d33e.png)

**Comment by ab-chao** [comment]
![图片](https://user-images.githubusercontent.com/22811751/58066838-a2b02900-7bbd-11e9-9d28-1b7d2c4cec67.png)

**Comment by ab-chao** [comment]
![图片](https://user-images.githubusercontent.com/22811751/58066905-edca3c00-7bbd-11e9-9885-d2957eb1560d.png)

**Comment by ab-chao** [comment]
![图片](https://user-images.githubusercontent.com/22811751/58066928-0fc3be80-7bbe-11e9-8720-c6eaba53f633.png)

**Comment by yangwenmai** [comment]
你可以直接提 PR 来修复这些错别字，没必要开一个 issue
